apiVersion: v1
kind: Service
metadata:
  {{- if .Values.name}}
  name: {{.Values.name}}
  {{- end}}
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if .Values.name}}
  name: {{.Values.name}}
  {{- end}}
  labels:
    app: nginx
spec:
  {{- if .Values.replicas}}
  replicas: {{.Values.replicas}}
  {{- end}}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        node-pool: general-preemptible
      containers:     
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.75"
            memory: "0.75Gi"
          requests:
            cpu: "0.5"
            memory: "0.5Gi"
